# Site settings
title: PixelPerc
email: pauladamdavisl@gmail.com
description: A simple tool to help build responsive websites

baseurl: "https://pauladamdavis.github.io/PixelPerc" # the subpath of your site, e.g. /blog/

sass:
    style: :compressed
